/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PembelajaranRouteImport } from './routes/pembelajaran'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KasusRouteImport } from './routes/kasus'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const PembelajaranRoute = PembelajaranRouteImport.update({
  id: '/pembelajaran',
  path: '/pembelajaran',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KasusRoute = KasusRouteImport.update({
  id: '/kasus',
  path: '/kasus',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kasus': typeof KasusRoute
  '/login': typeof LoginRoute
  '/pembelajaran': typeof PembelajaranRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kasus': typeof KasusRoute
  '/login': typeof LoginRoute
  '/pembelajaran': typeof PembelajaranRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kasus': typeof KasusRoute
  '/login': typeof LoginRoute
  '/pembelajaran': typeof PembelajaranRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/kasus' | '/login' | '/pembelajaran'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/kasus' | '/login' | '/pembelajaran'
  id: '__root__' | '/' | '/dashboard' | '/kasus' | '/login' | '/pembelajaran'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KasusRoute: typeof KasusRoute
  LoginRoute: typeof LoginRoute
  PembelajaranRoute: typeof PembelajaranRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pembelajaran': {
      id: '/pembelajaran'
      path: '/pembelajaran'
      fullPath: '/pembelajaran'
      preLoaderRoute: typeof PembelajaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasus': {
      id: '/kasus'
      path: '/kasus'
      fullPath: '/kasus'
      preLoaderRoute: typeof KasusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KasusRoute: KasusRoute,
  LoginRoute: LoginRoute,
  PembelajaranRoute: PembelajaranRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
